name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 103.162.20.144
          username: root
          password: Admin123
          script: |
            cd projects/nextjs
            npm run build
            pm2 start ecosystem.config.js
            pm2 restart web
